### ISSUE TITLE
`psa_key_attributes_t` is an opaque structure, so the tests shouldn't be relying on it having a `bits` member.

### ISSUE THREAD

**Issue by jainvikas8** [ARM-software/psa-arch-tests#116]
---Error---

`[ 19%] Building C object CMakeFiles/test_combine.dir/dev_apis/crypto/test_c002/test_c002.c.o
In file included from /home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/val/nspe/val_interfaces.h:21:0,
                 from /home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/dev_apis/crypto/test_c002/test_c002.c:18:
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/dev_apis/crypto/test_c002/test_c002.c: In function 'psa_import_key_test':
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/dev_apis/crypto/test_c002/test_c002.c:117:45: error: 'psa_key_attributes_t {aka struct psa_key_attributes_s}' has no member named 'bits'
             TEST_ASSERT_EQUAL(get_attributes.bits, check1[i].attr_bits, TEST_CHECKPOINT_NUM(6));
                                             ^
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/val/common/val.h:127:14: note: in definition of macro 'TEST_ASSERT_EQUAL'
         if ((arg1) != arg2)                                                         \
              ^~~~
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/dev_apis/crypto/test_c002/test_c002.c:117:45: error: 'psa_key_attributes_t {aka struct psa_key_attributes_s}' has no member named 'bits'
             TEST_ASSERT_EQUAL(get_attributes.bits, check1[i].attr_bits, TEST_CHECKPOINT_NUM(6));
                                             ^
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/val/common/val.h:130:55: note: in definition of macro 'TEST_ASSERT_EQUAL'
             val->print(PRINT_ERROR, "\tActual: %d\n", arg1);                        \
                                                       ^~~~
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/dev_apis/crypto/test_c002/test_c002.c:119:45: error: 'psa_key_attributes_t {aka struct psa_key_attributes_s}' has no member named 'bits'
             TEST_ASSERT_EQUAL(get_attributes.bits, check1[i].expected_bit_length,
                                             ^
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/val/common/val.h:127:14: note: in definition of macro 'TEST_ASSERT_EQUAL'
         if ((arg1) != arg2)                                                         \
              ^~~~
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/dev_apis/crypto/test_c002/test_c002.c:119:45: error: 'psa_key_attributes_t {aka struct psa_key_attributes_s}' has no member named 'bits'
             TEST_ASSERT_EQUAL(get_attributes.bits, check1[i].expected_bit_length,
                                             ^
/home/vikkat01/Desktop/Workspace/psa-arch-tests/api-tests/val/common/val.h:130:55: note: in definition of macro 'TEST_ASSERT_EQUAL'
             val->print(PRINT_ERROR, "\tActual: %d\n", arg1);                        \
                                                       ^~~~
CMakeFiles/test_combine.dir/build.make:134: recipe for target 'CMakeFiles/test_combine.dir/dev_apis/crypto/test_c002/test_c002.c.o' failed
make[2]: *** [CMakeFiles/test_combine.dir/dev_apis/crypto/test_c002/test_c002.c.o] Error 1
CMakeFiles/Makefile2:242: recipe for target 'CMakeFiles/test_combine.dir/all' failed
make[1]: *** [CMakeFiles/test_combine.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

This occurs for test_c0**02, 16,50** with 
Example: `cmake ../ -G"Unix Makefiles" -DTOOLCHAIN=HOST_GCC -DTARGET=tgt_dev_apis_stdc -DSUITE=CRYPTO -DPSA_INCLUDE_PATHS=~/mbed-crypto/include/ -DCPU_ARCH=armv7m`

And is related to this https://github.com/ARM-software/psa-arch-tests/pull/113

**Comment by jaypit02** [comment]
The fix for the issue has been submitted here #117. Hence closing this.
