### ISSUE TITLE
CPU Architecture doesn't need to be mentioned, if toolchain is HOST_GCC

### ISSUE THREAD

**Issue by jainvikas8** [ARM-software/psa-arch-tests#118]
`cmake ../ -G"Unix Makefiles" -DTOOLCHAIN=HOST_GCC -DTARGET=tgt_dev_apis_stdc -DSUITE=CRYPTO -DPSA_INCLUDE_PATHS=~/mbed-crypto/include/ -DCPU_ARCH=armv7m`

Related to this #113

At the moment CPU architecture needs to be mentioned for HOST_GCC toolchain which seems irrelevant for the this Linux target `tgt_dev_apis_stdc `.

**Comment by jaypit02** [comment]
The fix for the issue has been submitted here #117. Hence closing this.
