### ISSUE TITLE
Attest claim requirements has changed in PSA API 1.0.0. version

### ISSUE THREAD

**Issue by tamasban** [ARM-software/psa-arch-tests#122]
There are changes in the requirements of presence of the claims in attestation token. Please check it here:
https://github.com/ARMmbed/psa-attestation-api

Changes in SW_COMPONENTS array::
- signer_id: mandatory -> optional
- security epoch:  removed

**Comment by gowthamsiddarthd** [comment]
Hi Tamas,

Thank you for the feedback.

The description of Signed-ID section in the software component states "This field must be present to be compliant with the PSA-SM". Hence for PSA Function Certification, the presence of this field is mandatory.

I will capture this information in the psa-arch-tests documentation.

Regards,
Gowtham
