### ISSUE TITLE
Build fails if PSA_INCLUDE_PATHS uses relative paths

### ISSUE THREAD

**Issue by ghost** [ARM-software/psa-arch-tests#128]
If you run a build with a non canonical path (e.g ```../../tf-m/interface/include```) the `cmake` build will complete (detecting the header files) but the `make` invocation will then fail to find the header files:

```
fatal error: psa/initial_attestation.h: No such file or directory
#include "psa/initial_attestation.h"
```

**Comment by jaypit02** [comment]
Hi @raefcoles-arm,

Thanks for reporting this.

Currently, PSA_INCLUDE_PATHS accepts only absolute path and doesn't support the relative path.
However, if you want to pass relative path, you can use the following syntax:

PSA_INCLUDE_PATHS=`readlink -f ../../tf-m/interface/include`

I hope, this helps.

**Comment by raefcoles-arm** [comment]
In that case, can I recommend that this information be added to the PSA developer API readme page? This would be useful for others who are trying to build the project.

**Comment by jaypit02** [comment]
Hi @raefcoles-arm,

I hope, the suggestion would work for you. We will update the documentation for this soon.

Thanks,
Jay

**Comment by jaypit02** [comment]
Documentation has been updated as part of https://github.com/ARM-software/psa-arch-tests/pull/133. Hence closing this.
