### ISSUE TITLE
Duplicate val_target_get_config() declare in val_target.h

### ISSUE THREAD

**Issue by AlamyLiu** [ARM-software/psa-arch-tests#130]
https://github.com/ARM-software/psa-arch-tests/blob/master/api-tests/val/common/val_target.h

Around line 203 & 207.

**Comment by jaypit02** [comment]
Hi @alamyliu, 

Thanks for reporting this. Yes, function is declared twice and it's an issue. We would update the code for this soon. Let us know if you require fix urgently. 

Thanks,
Jay

**Comment by jaypit02** [comment]
Fix has been provided as part of https://github.com/ARM-software/psa-arch-tests/pull/133. Hence closing this.
