### ISSUE TITLE
QCBOR misalignment between psa-arch-test and tf-m

### ISSUE THREAD

**Issue by tamasban** [ARM-software/psa-arch-tests#143]
In TF-M repo the QCBOR library version was recently updated: https://review.trustedfirmware.org/c/trusted-firmware-m/+/2679/

Currently TF-M is aligned with this version of the original repo: https://github.com/laurencelundblade/QCBOR/commit/42272e466a8472948bf8fca076d113b81b99f0e0

PSA-ARCH still relies on older version:
https://github.com/ARM-software/psa-arch-tests/blob/7b50a2ae10410cf757e4105ddbe5bfc7e7c4157d/api-tests/CMakeLists.txt#L163

This misalignment causes that attestation test suite is failing with current TF-M master.

Could you update psa-arch?

**Comment by gowthamsiddarthd** [comment]
Issue resolved with PR: https://github.com/ARM-software/psa-arch-tests/pull/145
