### ISSUE TITLE
RSA key generation cannot guarantee a fixed size for the key representation

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARM-software/psa-arch-tests#155]
In `test_c016.h`, there is a [test case for RSA key generation](https://github.com/ARM-software/psa-arch-tests/blob/b892626a44b4681758b49f76a44a3f1a30f834ab/api-tests/dev_apis/crypto/test_c016/test_data.h#L78) which requires the size of the resulting exported key to be a fixed value (1192). This is not correct: the representation of an RSA is in DER format, which mandates that numbers have between 1 and 8 leading zero bits (i.e. no leading zero byte unless the bit-size is a multiple of 8, and one leading zero byte if the bit-size is a multiple of 8), and the leading bits of each number are effectively random, so there can be a few bytes of variation. The maximum possible representation size for a 2048-bit RSA key pair with e=65537 is 1194 bytes, with values in the range 1190–1193 being most likely and smaller values being possible with exponentially decreasing probability.

None of the other currently supported key types have this variable-size issue.

**Comment by gowthamsiddarthd** [comment]
Hi @gilles-peskine-arm ,

Thank you for providing the analysis on the test failure. Now PSA ACK covers this case by providing range for key sizes. This has been pushed as part of PR: https://github.com/ARM-software/psa-arch-tests/pull/156

Regards,
Gowtham
