### ISSUE TITLE
How to build the psa-arch-tests with the cmake and armclang in the cygwin?

### ISSUE THREAD

**Issue by yanpengfei66ok** [ARM-software/psa-arch-tests#158]
Here's my question:

I need your help，thank you!

After Installing several softwares for building the compilation environment according to the Software Requirements Document which is in the "https://github.com/ARM-software/psa-arch-tests/blob/master/api-tests/docs/sw_requirements.md", when I compiled the source code psa-arch-tests of PSA API compliance test suite, the cygwin prompted the following error result:

luofeng66ok@DESKTOP ~/TFMB/psa-arch-tests/api-tests/build
$ cmake ../ -G"Unix Makefiles" -DTOOLCHAIN=ARMCLANG -DTARGET=tgt_dev_apis_tfm_an521 -DCPU_ARCH=armv8m_ml -DSUITE=CRYPTO -DPSA_INCLUDE_PATHS="/cygdrive/c/cygwin64/home/anpengfei/TFMB/trusted-firmware-m/interface/include/psa/crypto.h"
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/cygwin64/home/luofeng66ok/TFMB/psa-arch-tests/api-tests/BUILD/CMakeF
iles/CMakeOutput.log".
See also "C:/cygwin64/home/luofeng66ok/TFMB/psa-arch-tests/api-tests/BUILD/CMakeF
iles/CMakeError.log".

the "CMakeError.log" displays:
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: C:/cygwin64/bin/cc 
Build flags: 
Id flags:  

The output was:
拒绝访问。

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: C:/cygwin64/bin/cc 
Build flags: 
Id flags: -c 

The output was:
拒绝访问。
......
my installed softwares are:

Host Operating System : Windows 10 64bit

Scripting tools :

luofeng66ok@DESKTOP-STB70QG ~/TFMB/psa-arch-tests/api-tests/build

$ Python --version

Python 3.7.0

Cross Compiler toolchain :

luofeng66ok@DESKTOP-STB70QG ~/TFMB/psa-arch-tests/api-tests/build

$ armclang --version

Product: MDK Plus 5.29

Component: ARM Compiler 6.13.1

Tool: armclang [5d895d00]

Target: unspecified-arm-none-unspecified

Build tools :

luofeng66ok@DESKTOP-STB70QG ~/TFMB/psa-arch-tests/api-tests/build

$ cmake --version

cmake version 3.10.0-rc1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ cygcheck --version

cygcheck (cygwin) 3.1.4

and I have imported Arm Compiler in my environment variable,

enter image description here

at the same time , I also imported Arm Compiler by this way:

C:\cygwin64\home\luofeng66ok.bashrc

export PATH=/cygdrive/c/Keil/ARM/ARMCLANG/bin:$PATH
export PATH=/cygdrive/c/cmake/bin:$PATH
export PATH=/cygdrive/c/armgcc/bin:$PATH
my steps for building psa-arch-tests are:

 git clone https://github.com/ARM-software/psa-arch-tests.git

 git clone https://github.com/laurencelundblade/QCBOR.git (I do not why do this)

 cd <TF-M base folder>
 git clone https://git.trustedfirmware.org/trusted-firmware-m.git
 git clone https://github.com/ARMmbed/mbed-crypto.git -b mbedcrypto-3.0.1
 git clone https://github.com/ARM-software/CMSIS_5.git -b 5.5.0
 git-lfs

my dir tfmb is

luofeng66ok@DESKTOP-STB70QG ~/tfmb
$ ls
CMSIS_5  mbed-crypto  psa-arch-tests  trusted-firmware-m

Start compiling psa-arch-tests

cd api-tests
    mkdir BUILD
    cd  BUILD
    cmake ../ -G"Unix Makefiles" -DTOOLCHAIN=ARMCLANG -DTARGET=tgt_dev_apis_tfm_an521 -DCPU_ARCH=armv8m_ml -DSUITE=CRYPTO -DPSA_INCLUDE_PATHS="/cygdrive/c/cygwin64/home/anpengfei/TFMB/trusted-firmware-m/interface/include/psa/crypto.h"    
as the errors above shows in my cygwin, I do not why?

luofeng66ok@DESKTOP-STB70QG ~/TFMB/psa-arch-tests/api-tests/build
$ cmake ../ -G"Unix Makefiles" -DTOOLCHAIN=ARMCLANG -DTARGET=tgt_dev_apis_tfm_an521 -DCPU_ARCH=armv8m_ml -DSUITE=CRYPTO -DPSA_INCLUDE_PATHS="/cygdrive/c/cygwin64/home/anpengfei/TFMB/trusted-firmware-m/interface/include/psa/crypto.h"
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/cygwin64/home/luofeng66ok/TFMB/psa-arch-tests/api-tests/BUILD/CMakeF
iles/CMakeOutput.log".
See also "C:/cygwin64/home/luofeng66ok/TFMB/psa-arch-tests/api-tests/BUILD/CMakeF
iles/CMakeError.log".

**Comment by kotegowder** [comment]
Hi,

In order to build psa-arch-tests on cygwin (Windows host), ensure you have 32-bit version of Cygwin and the necessary tools as mentioned in https://github.com/ARM-software/psa-arch-tests/blob/master/api-tests/docs/sw_requirements.md are available and set as part of PATH variable.

 The right build command to use for Crypto dev api build is :
cmake ../ -G"Unix Makefiles" -DTOOLCHAIN=ARMCLANG -DTARGET=tgt_dev_apis_tfm_an521 -DCPU_ARCH=armv8m_ml -DSUITE=CRYPTO -DPSA_INCLUDE_PATHS=/cygdrive/c/cygwin64/home/anpengfei/TFMB/trusted-firmware-m/interface/include

Please refer for build instructions in : 
https://github.com/ARM-software/psa-arch-tests/blob/master/api-tests/dev_apis/README.md

Let us know if that helps.

**Comment by kotegowder** [comment]
Let us know if you are able to make progress.
If all OK, we shall close this issue.

**Comment by kotegowder** [comment]
Closing the issue assuming it's working.
