### ISSUE TITLE
Print garbage message on MPS2 AN521 board

### ISSUE THREAD

**Issue by edison-ai** [ARM-software/psa-arch-tests#164]
When running PSA Arch Dev API test on MPS2 AN521 board, the TF-M boot message works normally. But the PSA Arch test will print out garbage messages.

Please confirm this and try to fix that if it exists.

**Comment by ChangwuShan** [comment]
I have confirmed in my side and this diff can eliminate the garbage messages issue.
--- a/api-tests/platform/drivers/uart/cmsdk/pal_uart.c
+++ b/api-tests/platform/drivers/uart/cmsdk/pal_uart.c
@@ -31,7 +31,7 @@ void pal_uart_cmsdk_init(uint32_t uart_base_addr)
     ((uart_t *) g_uart)->CTRL = CMSDK_UART_CTRL_TXEN_Msk;
     /* However, the UART resets to a BAUDDIV of 0, which is invalid. Set it to
     * the minimum valid number. */
-    ((uart_t *) g_uart)->BAUDDIV = 16;
 }

**Comment by kotegowder** [comment]
The changes are available in PR
https://github.com/ARM-software/psa-arch-tests/pull/202

**Comment by kotegowder** [comment]
Please review and confirm

**Comment by TTornblom** [comment]
Yes, this seems to fix the UART issue.

Thanks

**Comment by kotegowder** [comment]
Fixed with https://github.com/ARM-software/psa-arch-tests/pull/202

**Comment by kotegowder** [comment]
Fixed with https://github.com/ARM-software/psa-arch-tests/pull/202
Closing the issue.
