### ISSUE TITLE
Invalid buffer Index in  Crypto 21

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#175]
Hi, 

In the Crypto 21 tests, there are two defines SLOT_1 and SLOT_2 and they used to index key handles in **key_handle** variable. 
But the key_handle variable size is two and SLOT2 is defined as 2.

```
#define     SLOT_1      1
#define     SLOT_2      2

psa_key_handle_t                key_handle[2];
```

So below expression is wrong(overflow)

`&key_handle[SLOT_2]`

So defines need to be defined as below

```
#define     SLOT_1      0
#define     SLOT_2      1
```

If you are agree, I am happy to create a PR. 

Thanks

**Comment by kotegowder** [comment]
Addressed with https://github.com/ARM-software/psa-arch-tests/pull/187.
Closing the issue.
