### ISSUE TITLE
Wrong Order in Function Call in Crypto 58/59/61

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#178]
Hi, 

In the following test cases, the parameter order in function calls is wrong. Please see test 58, 59 and 61

```
status = val->crypto_function(VAL_CRYPTO_AEAD_UPDATE, &operation,
                 check1[i].plaintext_length,  check1[i].plaintext, output,
```

check1[i].plaintext and check1[i].plaintext_length should be replaced.

```
status = val->crypto_function(VAL_CRYPTO_AEAD_UPDATE, &operation,
                 check1[i].plaintext, check1[i].plaintext_length, output,
```

**Comment by kotegowder** [comment]
Fixed using https://github.com/ARM-software/psa-arch-tests/pull/190
Closing the issue.
