### ISSUE TITLE
size_t type for arrays

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#179]
Hi, 

In the following tests,  some buffers are implemented in size_t type which fails the tests. 

test58

typedef struct {
    char                    test_desc[75];
    psa_key_handle_t        key_handle;
    psa_key_type_t          key_type;
    uint8_t                 key_data[32];
    uint32_t                key_length;
    psa_key_usage_t         usage;
    psa_algorithm_t         key_alg;
    psa_algorithm_t         alg;
    uint8_t                 plaintext[30];
    uint8_t                 additional_data[32];
    uint8_t                 nonce[32];
    size_t                  nonce_size;
    size_t                  ad_length;
    size_t                  plaintext_length;
    size_t                  input_length;
    size_t                  output_size;
    **size_t                  expected_output[45];**
    size_t                  expected_length;
    psa_status_t            expected_status;
} test_data;

test 59

typedef struct {
    char                    test_desc[75];
    psa_key_handle_t        key_handle;
    psa_key_type_t          key_type;
    uint8_t                 key_data[32];
    uint32_t                key_length;
    psa_key_usage_t         usage;
    psa_algorithm_t         key_alg;
    psa_algorithm_t         alg;
    uint8_t                 plaintext[30];
    uint8_t                 additional_data[32];
    uint8_t                 nonce[32];
    size_t                  nonce_size;
    size_t                  ad_length;
    size_t                  plaintext_length;
    size_t                  input_length;
    size_t                  output_size;
    **size_t                  expected_output[45];**
    size_t                  expected_length;
    size_t                  tag_size;
    **size_t                  expected_tag[64];**
    size_t                  expected_tag_length;
    psa_status_t            expected_status;
} test_data;

test 61

typedef struct {
    char                    test_desc[75];
    psa_key_handle_t        key_handle;
    psa_key_type_t          key_type;
    uint8_t                 key_data[32];
    uint32_t                key_length;
    psa_key_usage_t         usage;
    psa_algorithm_t         key_alg;
    psa_algorithm_t         alg;
    uint8_t                 plaintext[30];
    uint8_t                 additional_data[32];
    uint8_t                 nonce[32];
    size_t                  nonce_size;
    size_t                  ad_length;
    size_t                  plaintext_length;
    size_t                  input_length;
    size_t                  output_size;
    **size_t                  expected_output[45]**;
    size_t                  expected_length;
    size_t                  tag_size;
    **size_t                  expected_tag[64];**
    size_t                  expected_tag_length;
    psa_status_t            expected_status;
} test_data;

I believe all these should be uint8_t type otherwise the tests fail.

**Comment by kotegowder** [comment]
Fixed with https://github.com/ARM-software/psa-arch-tests/pull/191
Closing the issue.
