### ISSUE TITLE
Missing Data in Test Data Structures

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#180]
Hi, 

The data for below fields are missing in test 59 and 61 tests. 

```
     size_t                  tag_size;
    uint8_t                 expected_tag[64];
     size_t                  expected_tag_length;
```

Below data needs to be added for mentioned fields.

`SIZE_32B, {0}, 0,`

**Comment by kotegowder** [comment]
Fixed with https://github.com/ARM-software/psa-arch-tests/pull/192
Closing the issue.
