### ISSUE TITLE
Wrong Test Data in Test 58, 59, 61

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#185]
When we run the these test we get fail for AES CCM. 
We are confused about the keys, nonce and ad values. 

Test 24 has similar AES CCM case; the plain text and cipher text of test 24 and test 58 are the same but the key, nonce and ad are different. 

While test 24 passes the tests, test 58, 59 and 61 fails. 

Interestingly, 13 byte nonce of test 24 is the same as 13 byte AD value of test 58. 
I assume there should be a wrong order in test_data.h of test 58. 

I assume it should be difficult to get the same ciphertext from the same plain text with different key, so when I use the key from key 24, I get the expected ciphertext. 
But the tag still different which must be about the AD which is different in test 24 and test 58. 
So, as expected if I use the AD from test 24, I could pass test 58.

So, it is just a question maybe I am wrong? 
While the plain text and cipher text are the same, are key, nonce and AD set mistakenly in test 58? Or it is what it is?

If something wrong, we might use the same key, nonce and AD from test 24 or we might modify only the expected cipher text in test 58 according to existing key,nonce and AD. 

The same issues are in test 59 and 61.

So what do you think? What is wrong about these test cases?

If the test data of 59 is wrong and it should be identical to test 24, I am happy to create a PR. 

Thanks
Murat

**Comment by zaya-mc** [comment]
@kotegowder you might be intersted. Thank you.

**Comment by kotegowder** [comment]
Changes are pushed as part of https://github.com/ARM-software/psa-arch-tests/pull/193
