### ISSUE TITLE
Missing argument in Protected Storage Test 13

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#207]
In test 13, 

The data length argument is missing which causes a runtime error 

```
    val->print(PRINT_TEST, "[Check 10] No duplicate entry of UID present\n", 0);
    status = STORAGE_FUNCTION(s013_data[VAL_TEST_IDX20].api[fCode], p_uid, 0, TEST_BUFF_SIZE,
                              read_buff);
```

After "read_buff", we need to pass address of "p_data_length". 

Also, I would expect p_data_length type as size_t but it is uint32_t.

**Comment by kotegowder** [comment]
@zaya-mc : Thank you for reporting this. We shall create a PR for this.

**Comment by kotegowder** [comment]
Fixed with https://github.com/ARM-software/psa-arch-tests/pull/209
