### ISSUE TITLE
Expected Error for Invalid Usage

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#213]
In test 46, for the "Test psa_mac_compute - Invalid usage\n" case, the tests expect PSA_ERROR_NOT_SUPPORTED for invalid policy usage. 

For the rest of crypto tests, the expected error was PSA_ERROR_NOT_PERMITTED.

So, to be consistent can we change it to PSA_ERROR_NOT_PERMITTED?

**Comment by jk-arm** [comment]
lets revisit this once the issue resolved https://github.com/ARMmbed/mbedtls/issues/3258

**Comment by jk-arm** [comment]
changes are committed : https://github.com/ARM-software/psa-arch-tests/commit/dfb944c8e9e3874d3958a456c5d1299646d99b50
