### ISSUE TITLE
No portable inlined assembly lines

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#23]
There are 1-2 inlined GCC assembly and it is not portable for other platforms. 
Please see val/nspe/val_entry.c file 

`asm volatile("WFI");`

We cannot build it for Armclang. 
We could have macros to differentiate for different compilers/toolchains but some platforms like ZAYA Secure Kernel may not also allow user applications to have platform dependent codes. 

Therefore, we might abstract this functionality in PAL (e.g. pal_devicesleep() etc).

**Comment by jaypit02** [comment]
Thanks for pointing this out. We thought about this and have moved this code into platform/ already, internally. The updated code will be pushed to master as part of 0.7 release. 

Let me know if you need patch for this now.
