### ISSUE TITLE
Fail to remove heap_size field for FF test

### ISSUE THREAD

**Issue by ccli8** [ARM-software/psa-arch-tests#235]
Following https://github.com/ARM-software/psa-arch-tests/tree/master/api-tests/ff, I run the command to remove `heap_size` field:

```sh
python tools/scripts/manifest_update.py
```

But meet error:
```sh
Updating platform/manifests/driver_partition_psa.json manifest file
Traceback (most recent call last):
  File "C:\Python37\lib\shutil.py", line 566, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'platform/manifests/driver_partition_psa.json.update' -> 'platform/manifests/driver_partition_psa.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/scripts/manifest_update.py", line 58, in <module>
    update_manifest_file(manifest_dir_path)
  File "tools/scripts/manifest_update.py", line 41, in update_manifest_file
    shutil.move(file+".update", file)
  File "C:\Python37\lib\shutil.py", line 581, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'platform/manifests/driver_partition_psa.json.update'
```

Checking the file `ools/scripts/manifest_update.py`, it seems that `f_i.close()` and `f_o.close()` are missing. If I add them, this command is OK.

<pre>
def update_manifest_file(manifest_dir_path):
	"""
	- Remove heap_size field from manifest if dynamic memory function is not supported.
	"""
	file_list =	[manifest_dir_path+"/driver_partition_psa.json",
				manifest_dir_path+"/client_partition_psa.json",
				manifest_dir_path+"/server_partition_psa.json"]

	for file in file_list:
		print("Updating "+file+" manifest file")
		f_i = open(file, 'r')
		f_o = open(file+".update", 'w')
		f1 = f_i.readlines()
		for line in f1:
				if (re.findall('heap_size', line)):
					continue
				f_o.write(line)
                <b>
		f_i.close()
		f_o.close()
                </b>
		shutil.move(file+".update", file)
</pre>

### My environment:
**windows 10 msys2**
**python**
3.7.7
**psa-arch-tests**
d6612f4 Merge pull request #233 from oyvindronningstad/gitignore-BUILD

**Comment by jk-arm** [comment]
will update in the upcoming release
