### ISSUE TITLE
Could test_data.h be common for all crypto test suites?

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#24]
It seems each test suites has its "test_data.h" but test data in these headers are generally the same so could we create a single "test_data.h" which located in a common place for all test suites?

We are asking that because we are embedding all test suites into a single application (we are not using ELF Combiner scripts) and symbol names in the header files conflict with each other.

(We have some pre-compiler tricks to make the symbol names unique but it duplicates the same test data 10-15 times in the output.)

**Comment by jaypit02** [comment]
The global variables have been replaced with static variables in https://github.com/ARM-software/psa-arch-tests/pull/29 and this PR is already been merged to master. Hence closing this.
