### ISSUE TITLE
Support Firmware Framework test for MUSCA S1 target (IPC)

### ISSUE THREAD

**Issue by jainvikas8** [ARM-software/psa-arch-tests#247]
Please add support of **IPC** test suite for ARM_MUSCA_S1 target. This target is supported in Mbed OS and TF-M.

https://github.com/ARMmbed/mbed-os-tf-m-regression-tests/issues/49

**Comment by evedon** [comment]
Could you let us know when you can work on this?

**Comment by jk-arm** [comment]
https://github.com/ARM-software/psa-arch-tests/tree/master/api-tests/platform/targets/tgt_dev_apis_tfm_musca_s1, the s1 platform is suppored already

**Comment by jainvikas8** [comment]
We are taling about IPC - firmware framework - The target goes by **tgt_ff_tfm_musca_s1** ?

**Comment by jk-arm** [comment]
in CMKAE command, please mention the target as tgt_ff_tfm_musca_s1, the musca_s1 will be picked up

**Comment by jainvikas8** [comment]
Is this documented somewhere? If `tgt_ff_tfm_musca_s1` and `tgt_ff_tfm_musca_b1` uses the same alias..

**Comment by jainvikas8** [comment]
> in CMKAE command, please mention the target as tgt_ff_tfm_musca_s1, the musca_s1 will be picked up

Target not supported when using `tgt_ff_tfm_musca_s1` on https://github.com/ARM-software/psa-arch-tests/commit/13c6e2c439c5122b9f0e414ad6a687af809975fd
```
 -- [PSA] : ----------Process input arguments- start-------------..
 CMake Error at CMakeLists.txt:144 (message):..
 [PSA] : Error: Unsupported value for -DTARGET=tgt_ff_tfm_musca_s1,..
supported targets are :..
common;tgt_dev_apis_stdc;tgt_dev_apis_tfm_an521;tgt_dev_apis_tfm_an524;tgt_dev_apis_tfm_an539;tgt_dev_apis_tfm_musca_a;tgt_dev_apis_tfm_musca_b1;tgt_dev_apis_tfm_musca_s1;tgt_dev_apis_tfm_nrf;tgt_dev_apis_tfm_psoc64;tgt_ff_tfm_an521;tgt_ff_tfm_musca_a;tgt_ff_tfm_musca_b1..
```

**Comment by jk-arm** [comment]
1. if you are compiling the standalone psa arch test for musca_s1 then the target should be "tgt_dev_apis_tfm_musca_s1"
2. if you are trying to compile through the TFM then TFM readme mentioned target name should be used, 

for 1st we can help you and the 2nd you should contact TFM team for proper alias mapping,

give us some time, we will try to reproduce and solve if required

**Comment by jk-arm** [comment]
i am able to compile the build for musca_s1, if you are compiling in trusted firmware environment please follow the trusted firmware readme: 
https://ci-builds.trustedfirmware.org/static-files/ZlFG20BBiImhpv8EIHIISEnTVkrBD1kQUnVvX676rSYxNjA5OTIzMjgyMDc4Ojk6YW5vbnltb3VzOmpvYi90Zi1tLWJ1aWxkLWRvY3MtbmlnaHRseS9sYXN0U3RhYmxlQnVpbGQvYXJ0aWZhY3Q=/trusted-firmware-m/build/docs/user_guide/html/docs/getting_started/tfm_build_instruction.html

if you are compiling from psa arch test, please follow the readme file from psa arch test.

**Comment by jainvikas8** [comment]
So to run the Firmware Framework test suite - IPC for ARM_MUSCA_S1 - we need to use - `tgt_dev_apis_tfm_musca_s1`?

**Comment by jk-arm** [comment]
please use the link for running the IPC testcases
https://ci-builds.trustedfirmware.org/static-files/ZlFG20BBiImhpv8EIHIISEnTVkrBD1kQUnVvX676rSYxNjA5OTIzMjgyMDc4Ojk6YW5vbnltb3VzOmpvYi90Zi1tLWJ1aWxkLWRvY3MtbmlnaHRseS9sYXN0U3RhYmxlQnVpbGQvYXJ0aWZhY3Q=/trusted-firmware-m/build/docs/user_guide/html/docs/getting_started/tfm_build_instruction.html#build-for-psa-ff-ipc-compliance-tests

**Comment by jk-arm** [comment]
use the macro -DTFM_PLATFORM=musca_s1

**Comment by jk-arm** [comment]
internal jira to track the same with TFM team
https://jira.arm.com/browse/IOTPSW-3652

**Comment by jk-arm** [comment]
the support added,
