### ISSUE TITLE
Issue 223 reoccurs, please reopen it.

### ISSUE THREAD

**Issue by jainvikas8** [ARM-software/psa-arch-tests#248]
https://github.com/ARM-software/psa-arch-tests/issues/223

**Comment by jk-arm** [comment]
let me try to investigate further, IMO we have not changed anything on the compilation side, will come back on this

**Comment by LDong-Arm** [comment]
The symptom is like #223 but it's _not_ the same issue.
To build on macOS, we just need to do this: https://stackoverflow.com/a/60002595

@jk-arm Feel free to close this ticket!

**Comment by LDong-Arm** [comment]
This one can be closed

**Comment by jk-arm** [comment]
thankyou will do the same
