### ISSUE TITLE
Crypto tests require deprecated types and functions

### ISSUE THREAD

**Issue by Einhornhool** [ARM-software/psa-arch-tests#254]
Hi all =)
I am trying to build the PSA Crypto tests and I am getting some unknown type and implicit declaration errors from `api-tests/platform/targets/common/nspe/crypto/pal_crypto_intf.c`.

I checked it and according to the "Changes between 1.0 beta 3 and 1.0.0" section of the PSA Crypto specification, the `psa_key_handle_t` type and the `psa_open_key` and `psa_close_key` functions have been removed.
The functions `psa_asymmetric_sign` and `psa_asymmetric_verify` have been renamed to `psa_sign_hash` and `psa_verify_hash`. 

Apparently the tests still use the old types and functions, that I didn't implement, as they are not part of the specification anymore. Is there a configuration option I missed to specify which API version to use? Or are you planning on updating the code?

**Comment by jk-arm** [comment]
The current psa arch test supports only the 1.0 beta3

**Comment by Einhornhool** [comment]
Thank you for the answer. Are you planning on updating it any time soon?

**Comment by jk-arm** [comment]
we are doing the development at present, we will update you Soon, our reference platform doest not support crypto 1.0 yet.

**Comment by Einhornhool** [comment]
Thank you!

**Comment by jk-arm** [comment]
could you please try the tag : v21.07_API1.2_ADAC_ALPHA and share your comments

**Comment by jk-arm** [comment]
considering this for closure, please verify against the latest tag and come back

**Comment by Einhornhool** [comment]
Hey, I'm sorry I didn't get back to you sooner, I'm currently working on something else. But thank you for notifying me, I will try this as soon as I can.

**Comment by jk-arm** [comment]
thankyou


Regards,
JK
