### ISSUE TITLE
PSA-FF test not working on AN521(FVP)

### ISSUE THREAD

**Issue by ChangwuShan** [ARM-software/psa-arch-tests#257]
Hi,
The latest TF-M has some changes to the build system, which will cause IPC Test to fail ( PSA-FF test not working on AN521 FVP).

**Comment by ChangwuShan** [comment]
The build command to reproduce:
cmake -S . -B cmake_build -DTFM_PLATFORM=mps2/an521 -DTFM_TOOLCHAIN_FILE=toolchain_GNUARM.cmake -DTEST_PSA_API=IPC -DTFM_PSA_API=ON

**Comment by jk-arm** [comment]
hope this ticket can be closed now

**Comment by ChangwuShan** [comment]
Yes, the workaround patch already merged in the TFM side.
