### ISSUE TITLE
PSA FF tests halted in MemManageFault

### ISSUE THREAD

**Issue by andvib** [ARM-software/psa-arch-tests#273]
A number of the Firmware Framework tests (i68-i73, i75-i77, i79) results in a MemManageFault. I'm running the tests together with TF-M, which by default handles these faults with an infinite loop. I understand that this behaviour is as expected, but the infinite loop causes the tests to stop execution until a manual reset is performed. This causes some problems when automating these tests to run on CI.

Is there a way to execute these tests, while at the same time avoiding that the MemManageFault-handler is called and enters the infinite loop?

**Comment by jk-arm** [comment]
Hi @andvib , currently we are busy with the release activity, we will revisit this topic after July 10th.

**Comment by jk-arm** [comment]
@andvib could you please try again with the latest tag "v21.07_API1.2_ADAC_ALPHA" ?

**Comment by jk-arm** [comment]
we will consider this for closure

**Comment by andvib** [comment]
Sorry for late reply!

I tested with the tag and latest master, and I'm still seeing the same behaviour.

**Comment by jk-arm** [comment]
@andvib , thank for the update,
we had tried in the local setup and those testcases were passing on the label, I think it's good to revisit again. 
could you please reopen this or recreate a new ticket?
