### ISSUE TITLE
psa_hash_suspend and psa_hash_resume are optional feature in mbedtls, not implemented now

### ISSUE THREAD

**Issue by Summer-ARM** [ARM-software/psa-arch-tests#281]
psa_hash_suspend and psa_hash_resume were requested for a SIM protocol, and don't have people asking for support for that in Mbed TLS.
Better to have a flag to control test for these two functions. test 62 and 63

**Comment by jk-arm** [comment]
@Summer-ARM , psa arch test widely used by other partners who have their own firmware and PSA implementation

**Comment by jk-arm** [comment]
i would consider this for closure, once this https://github.com/ARM-software/psa-arch-tests/issues/252 gets implemented, you will have the option to run the validated test case only.
