### ISSUE TITLE
The latest releases to use

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#296]
Hi all,

We are trying to update the PSA API and and PSA Arch Tests in our locale with the latest tests, just we are a bit confused.

For the PSA API, should we include the "crypto.h" under api-specs/crypto/v1.0-beta1/include/psa.
If not, where can we find the latest crypto.h header?

We cannot build the master branch in psa-arch-tests, it seems some calls are renamed, like PSA_ECC_CURVE_SECP_R1 -> PSA_ECC_FAMILY_SECP_R1, but the definition not updated so getting compile time errors. 

What is the latest stable commit/tag/release to run psa-arch-tests.

https://github.com/ARM-software/psa-arch-tests/releases
says the latest is "v1.0 release of API test suite" which is release 2020 March (1.5 years ago). Is it the latest stable release to run?

Thank you in advance.
Murat

**Comment by jk-arm** [comment]
could you please refer to this location for your reference, we stopped copying the headers in the location.
https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/interface/include/psa
