### ISSUE TITLE
A compiler switch to enable or disable TLS12 PRF Key Derivation Tests

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#305]
Can we have a Compiler Switch for TLS12 PRF Key Derivation Tests? It could be more flexible for custom target that does not implement it.
There are tests In the crypto test 20.

**Comment by zaya-mc** [comment]
We can create a PR if wanted.

**Comment by jk-arm** [comment]
Please create a PR, we will have a look at it, if possible we will bring along with this release


Regards,
JK

**Comment by jk-arm** [comment]
closing this as https://github.com/ARM-software/psa-arch-tests/pull/313 merged
