### ISSUE TITLE
My Crypto Test C021 Check 6 result is pass

### ISSUE THREAD

**Issue by iloveyou-github** [ARM-software/psa-arch-tests#330]
I dont know why crypto_test_c021_check_6 ("") 's expected_status is PSA_ERROR_INVALID_ARGUMENT, My platform ,use mbedtls 3.2.1 status is PASS.

{"Test psa_key_derivation_output_key - ECC keypair\n", PSA_KEY_TYPE_DERIVE,
{0x49, 0x8E, 0xC7, 0x7D, 0x01, 0x95, 0x0D, 0x94, 0x2C, 0x16, 0xA5, 0x3E, 0x99,
 0x5F, 0xC9, 0x77},
 AES_16B_KEY_SIZE, PSA_KEY_USAGE_DERIVE,
 PSA_ALG_KEY_AGREEMENT(PSA_ALG_ECDH, PSA_ALG_HKDF(PSA_ALG_SHA_256)),
 PSA_KEY_DERIVATION_INPUT_SECRET, 224, {0}, 0,
 PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_FAMILY_SECP_R1), 224, PSA_KEY_USAGE_EXPORT,
 PSA_ALG_ECDSA_ANY,
 PSA_ERROR_INVALID_ARGUMENT
},

I wand to know which item(s) lead to expected_status is PSA_ERROR_INVALID_ARGUMENT

thx~

**Comment by jk-arm** [comment]
assuming your question gets answered, hence closing this ticket.
