### ISSUE TITLE
Incompatible with latest CMake (3.25) release

### ISSUE THREAD

**Issue by SebastianBoe** [ARM-software/psa-arch-tests#335]
Hello,

it seems psa-arch-tests is incompatible with the latest CMake relase (3.25).

> Hi,
> 
>  
> 
> when I updated from CMake 3.24.0 to the new (two weeks old) CMake 3.25.0 I am no longer
> 
> able to build TF-M with -DTEST_PSA_API=CRYPTO.
> 
>  
> 
> (Downgrading CMake fixes the issue)
> 
>  
> 
> Is there an interoperability issue with the latest CMake release and the TF-M build system?
> 
>  
> 
> Reproduced with
> 
> TF-Mv1.7.0-RC1
> 
> TF-Mv1.6.0
> 
>  
> 
> Steps to reproduce:
> 
>  
> 
> install CMake 3.25.0.
> cd trusted-firmware-m
> rm -rf cmake_build && cmake -G Ninja -S . -B cmake_build -DTEST_PSA_API=CRYPTO  -DTFM_PLATFORM=nordic_nrf/nrf5340dk_nrf5340_cpuapp -DTFM_TOOLCHAIN_FILE=toolchain_GNUARM.cmake -DCMAKE_BUILD_TYPE=Debug && ninja -C cmake_build
>  
> 
> Only reproduces with TEST_PSA_API and CMake 3.25.0. Builds fine with 3.24.0 or non-PSA API builds.
> 
>  
> 
> error:
> 
>  
> 
>   file INSTALL cannot find
> 
>   "/home/sebo/ncs/modules/tee/tf-m/trusted-firmware-m/cmake_build/tf-m-tests/app/psa_api_tests/src/psa_generate_database-build/target_database.h":
> 
>   No such file or directory.
> -- Sebastian Bøe

> Hi Sebastian,
> 
>  
> 
> Thanks a lot for reporting this.
> 
> I also reproduced it on AN521. `target_database.h` is generated and installed by PSA Arch test build. It is transparent to TF-M build.
> 
>  
> 
> The generation step is skipped with CMake 2.25 while it is generated successfully with CMake 2.21:
> 
> `
> 
> [218/494] Performing install step for 'psa_generate_database'
> 
> [1/5] [PSA] : Creating generator source /home/davhu01/project/tf-m/gerrit-tf-m/profile_test/build/tf-m-tests/app/psa_api_tests/targetConfigGen.c
> 
> [2/5] Building C object CMakeFiles/TargetConfigGen.dir/home/davhu01/project/tf-m/gerrit-tf-m/profile_test/build/tf-m-tests/app/psa_api_tests/targetConfigGen.c.o
> 
> [3/5] Linking C executable TargetConfigGen
> 
> [4/5] [PSA] : Creating output header target_database.h
> 
> [4/5] Install the project...
> 
> `
> 
> Since install() shall happen after all builds complete, I guess some dependencies are broken with CMake 2.25.
> 
> Can you please raise this issue to [https://github.com/ARM-software/psa-arch-tests/issues](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FARM-software%2Fpsa-arch-tests%2Fissues&data=05%7C01%7CSebastian.Boe%40nordicsemi.no%7C1c3f25d29dfb4dbe05fb08dad100dcd0%7C28e5afa2bf6f419a8cf6b31c6e9e5e8d%7C0%7C0%7C638052098885574345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rpA%2FYCUoDANMA5lcOqBko02fTcYEywCwexD9wxbfjYs%3D&reserved=0)? PSA Arch tests developers should know the root cause better.
> 
>  
> 
> Best regards,
> 
> Hu Ziji

**Comment by jk-arm** [comment]
@SebastianBoe interesting, the build gets success with "Unix makefiles" but failed with the ninja. i believe its more todo with the cmake than the psa-arch-test
