### ISSUE TITLE
Only /n line endings instead of /r/n

### ISSUE THREAD

**Issue by mswarowsky** [ARM-software/psa-arch-tests#336]
Hei,

While doing release testing of the TF-M 1.7-rc2 on nRF5340 and nRF9160 I noticed that the line endings sent by the tests just have a `\n` not a `\r\n` causing format issues displaying the output on several serial terminals in linux, with default settings. 

The test I have seen this behavior was Crypto/Storage/Initial Attestation.

So might be a good choice to replace all `\n` to `\r\n` in the logging or uart driver. As I have only nRF platforms available I don't know if that is already been done for other platforms.

**Comment by jk-arm** [comment]
@mswarowsky currently the printing functionality is left to platform interface implementation, meaning the partner platform abstraction layer implementation will take care. please refer to the "pal_print"

**Comment by jk-arm** [comment]
@mswarowsky please let me know, so that i can move this ticket to appropriate state or clsed.

**Comment by mswarowsky** [comment]
Yeah closed it
