### ISSUE TITLE
Preprocessor macro definitions must avoid the PSA namespace

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARM-software/psa-arch-tests#337]
Some headers in the test suite define C preprocessor macros that are also defined in PSA specifications. This is not valid because the implementation may have a definition for these macros that has the same value, but a different expansion.

We discovered this in Mbed TLS because we we're restyling the code, and [the whitespace changes caused the compiler to complain](https://github.com/Mbed-TLS/mbedtls/issues/6875):

```
In file included from /var/lib/build/psa-arch-tests/api-tests/val/nspe/val_crypto.c:22:0:
/var/lib/build/psa-arch-tests/api-tests/val/nspe/val_crypto.h:56:0: error: "PSA_ALG_NONE" redefined [-Werror]
 #define PSA_ALG_NONE ((psa_algorithm_t)0)
 
In file included from /var/lib/build/include/psa/crypto.h:68:0,
                 from /var/lib/build/psa-arch-tests/api-tests/platform/targets/tgt_dev_apis_stdc/nspe/pal_config.h:88,
                 from /var/lib/build/psa-arch-tests/api-tests/platform/targets/common/nspe/pal_common.h:27,
                 from /var/lib/build/psa-arch-tests/api-tests/val/common/val.h:21,
                 from /var/lib/build/psa-arch-tests/api-tests/val/common/val_target.h:21,
                 from /var/lib/build/psa-arch-tests/api-tests/val/nspe/val_crypto.c:18:
/var/lib/build/include/psa/crypto_values.h:822:0: note: this is the location of the previous definition
 #define PSA_ALG_NONE                            ((psa_algorithm_t) 0)
 
In file included from /var/lib/build/psa-arch-tests/api-tests/val/nspe/val_crypto.c:22:0:
/var/lib/build/psa-arch-tests/api-tests/val/nspe/val_crypto.h:57:0: error: "PSA_KEY_ID_NULL" redefined [-Werror]
 #define PSA_KEY_ID_NULL ((psa_key_id_t)0)
 
In file included from /var/lib/build/include/psa/crypto.h:68:0,
                 from /var/lib/build/psa-arch-tests/api-tests/platform/targets/tgt_dev_apis_stdc/nspe/pal_config.h:88,
                 from /var/lib/build/psa-arch-tests/api-tests/platform/targets/common/nspe/pal_common.h:27,
                 from /var/lib/build/psa-arch-tests/api-tests/val/common/val.h:21,
                 from /var/lib/build/psa-arch-tests/api-tests/val/common/val_target.h:21,
                 from /var/lib/build/psa-arch-tests/api-tests/val/nspe/val_crypto.c:18:
/var/lib/build/include/psa/crypto_values.h:2088:0: note: this is the location of the previous definition
 #define PSA_KEY_ID_NULL                         ((psa_key_id_t) 0)
```

`((psa_algorithm_t)0)` and  `((psa_algorithm_t) 0)` are two valid definitions of `PSA_ALG_NONE`, but you can't include headers that define both together in the same program (the exact whitespace is not significant, but the presence vs absence of whitespace is). And any other definition such as `((uint32_t)(42 & ~42))` would be compliant.

There is an exception for `PSA_SUCCESS` and for `PSA_ERROR_xxx`, and only for those: they must have the exact sequence of tokens listed in the PSA error specification (in particular, with no space between the cast and the minus sign). Other macros such as `PSA_ALG_NONE` are not covered by this exceptions.

As of d97aef09709897dcc1c782326b38691382aaa574, at least `PSA_ALG_NONE` and `PSA_KEY_ID_NULL` in [`val/nspe/val_crypto.h`](https://github.com/ARM-software/psa-arch-tests/blob/main/api-tests/val/nspe/val_crypto.h) are problematic. (As would be `PSA_ALG_AEAD_WITH_DEFAULT_LENGTH_TAG` and `PSA_ALG_AEAD_WITH_SHORTENED_TAG` if they were commented out.)

Also `PSA_VERSION_NONE`, `PSA_SUCCESS` and `PSA_NULL_HANDLE` in [`api-tests/platform/targets/common/nspe/pal_common.h`](https://github.com/ARM-software/psa-arch-tests/blob/main/api-tests/platform/targets/common/nspe/pal_common.h) may be problematic: they're guarded by `#ifdef`, but that only helps if the psa-arch-tests header is included second, not if it's included first.

**Comment by avinaw01-arm** [comment]
The issue has been resolved and merged in the current repository: https://github.com/ARM-software/psa-arch-tests/pull/363
Please get back to us if you still face any issue.
