### ISSUE TITLE
psa_call with non-NULL outvec but a 0-size in i051/i054

### ISSUE THREAD

**Issue by raymao7703** [ARM-software/psa-arch-tests#87]
Hi,

In test case i051/i054, it is supposed to check the outvec.base by psa_call.
However, the outvec size should be 1 instead of 0.
----------------

Line 118 of test_i051.c and line 75 of test_i054.c 
Change from:
psa->call(handle, NULL, 0, outvec, 0);
to:
psa->call(handle, NULL, 0, outvec, 1);

Regards,
Raymond

**Comment by jaypit02** [comment]
Hi @raymao7703,

Thanks for reporting this. Yes this is a bug and we had found it and fixed it internally.  We are planning to push the fix for these tests as part of our next release in few weeks time. Let us know if you need patch now.

**Comment by jaypit02** [comment]
The fix for this issue is provided as part of PR:#94
