### ISSUE TITLE
(uid + 1) is not remove before returning in s004

### ISSUE THREAD

**Issue by raymao7703** [ARM-software/psa-arch-tests#89]
Hi,

In test case s004, it does not remove uid+1 before returning.
Below lines need to be added before "return VAL_STATUS_SUCCESS" in function "psa_sst_get_data_check":
----------------------
    status = SST_FUNCTION(s004_data[10].api, uid + 1);
    TEST_ASSERT_EQUAL(status, s004_data[10].status, TEST_CHECKPOINT_NUM(11));
----------------------

Regards,
Raymond

**Comment by chetansinghrathore** [comment]
The test is fixed.
PR#92 created with fix.

**Comment by jaypit02** [comment]
The fix for this issue in necessary branches has been provided as part of PR:#94 and #93.
